version: "3"
services:
  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "4000:4000"
      - "5555:5555"
    depends_on:
      - db
volumes:
  postgres_volume:
