"use client";
import type { Metadata } from "next";
import { SessionProvider, getSession } from "next-auth/react";
import { Provider as ZenStackHooksProvider } from "../lib/hooks";
import { FetchFn } from "@zenstackhq/swr/runtime";
import ThemeProvider from "@/components/layout/ThemeToggle/theme-provider";

const myFetch: FetchFn = (url, options) => {
  options = options ?? {};
  options.headers = {
    ...options.headers,
  };
  return fetch(url, options);
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <ZenStackHooksProvider value={{ endpoint: "/api/model", fetch: myFetch }}>
        <SessionProvider>{children}</SessionProvider>
      </ZenStackHooksProvider>
    </ThemeProvider>
  );
}
